blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page for creating a new post
    path('new_post/', views.new_post, name='new_post'),
    # Page for edit the posts
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    # Deletes post
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("blog.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = "users"

urlpatterns = [
    # Log in
    path('login/', views.log_in, name='login'),
    # Log out
    path('logout/', views.log_out, name='logout'),
    # Register page
    path('register/', views.register, name='register'),
    # Profile page
    path('profile/<int:user_id>/', views.profile, name='profile'),
    # Edit profile page
    path('profile/<int:user_id>/edit_profile', views.edit_profile, name='edit_profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

blog/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    """User posts"""

    title = models.CharField(max_length=200)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    message = models.TextField()

    def __str__(self):
        """Returns string info about posts"""
        max_length = 100
        if len(self.message) > max_length:
            return f"{self.title}: {self.message[:max_length]}..."
        else:
            return f"""{self.title}: {self.message}"""

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'message']
        labels = {'message': ''}

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Post
from .forms import PostForm


def index(request):
    # Variables for displays posts on homepage
    posts = Post.objects.order_by('timestamp')
    context = {'posts': posts}

    # Displays homepage
    return render(request, 'blog/index.html', context)

@login_required
def new_post(request):
    # Creates a new post on the site
    if request.method != "POST":
        # Creates an empty form
        form = PostForm()
    else:
        # If form isn't empty
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('blog:index')

    # Displays an empty or an invalid form
    context = {'form': form}
    return render(request, 'blog/new_post.html', context)

@login_required
def edit_post(request, post_id):
    # Edit the post
    post = Post.objects.get(id=post_id)
    if post.author != request.user:
        raise Http404

    if request.method != 'POST':
        # If form is empty
        form = PostForm(instance=post)
    else:
        # Sends POST-data, saves changes
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:index')

    context = {'post': post, 'form': form}
    return render(request, 'blog/edit_post.html/', context)

@login_required()
def delete_post(request, post_id):
    # Deletes existing posts
    post = Post.objects.get(id=post_id)
    post.delete()
    # Changes homepage
    return redirect('blog:index')

blog/templates/blog/base.html
{% load bootstrap4 %}

<!doctype html>
<html data-bs-theme="light" lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
          shrink-to-fit=no">
    <title>BLog.</title>
    <meta name="theme-color" content="#712cf9">

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5 border">

          <!-- Site logo -->
          <div class="container">
            <div class="col-6 text-right">
              <a class="navbar-brand" href="{% url 'blog:index' %}">
               <h3>
                 <img src="https://svgsilh.com/svg/2001981.svg"
                     alt="Logo" width="45" height="40" class="d-inline-block align-text-top">
               </h3>
              </a>
            </div>
            <!-- Toggle button -->
            <div class="col-5 text-center">
              <button class="navbar-toggler" type="button" data-toggle="collapse"
                      data-target="#navbarCollapse" aria-controls="navbarCollapse"
                      aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span></button>


              <!-- Login and Sign-in  or User Profile and Logout-->
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="d-grid gap-2 d-md-block ml-auto">
                  {% if not user.is_authenticated %}
                      <a class="btn" type="button" href="{% url 'users:login' %}">
                        Log In
                      </a>
                      <a class="btn btn-dark" type="button" href="{% url 'users:register' %}">
                        Sign-in
                      </a>
                  {% else %}
                      <a class="btn" type="button" href="{% url 'users:profile' user.id %}">
                        Hello, {{ user.username }}
                      </a>
                      <a class="btn btn-dark" type="button" href="{% url 'users:logout' %}">
                        Log Out
                      </a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
    </nav>
    <main role="main" class="container">

      <!-- Header -->
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header%}
      </div>

        {% block content %}{% endblock content %}

    </main>
  </body>
</html>

blog/templates/blog/edit_post.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}

{% block page_header %}

<h2 class="display-5">
  Edit post
</h2>

{% endblock page_header %}

{% block content %}

<form action="{% url 'blog:edit_post' post.id %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button class="btn btn-dark">Save changes</button>
  {% endbuttons %}
</form>

{% endblock content %}

blog/templates/blog/index.html
{%extends 'blog/base.html' %}


{% block page_header %}
<div class="jumbotron">
    <h1 class="display-5">
        Welcome to the BLog.
    </h1>

    <p class="lead">
        Greeting you on the BLog. It's the first site by bils1n@.
        There is the blog window and the users application here, everyone users can add a new post,
        change already created posts and also delete these posts. Well, it's not all yet...
        Coming soon.
    </p>
</div>
{% endblock page_header %}

{% block content %}
    <!-- Register and chat block -->
    <div class="container py-4">
        <div class="row align-items-md-stretch">
            <div class="col-md-6">
                <div class="h-100 p-5 text-white bg-dark rounded-3">
                    {% if user.is_authenticated %}
                        <p class="lead">
                            You can leave post! =)
                        </p>
                        {% if user.is_authenticated %}
                            <a class="btn btn-primary btn-sm" type="button"
                               href="{% url 'blog:new_post' %}">Add Post</a>
                        {% endif %}
                    {% else %}
                        <p>
                            If you want to leave post, you have to
                            <a href="{% url 'users:register' %}">register</a>
                            on the site.
                        </p>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="h-100 p-5 text-white bg-secondary rounded-3">
                    <p>There will the chat here</p>
                </div>
            </div>
        </div>
    </div>
    <!--  Register and chat block end  -->
    <!-- Posts block -->
    <div class="row mb-2">
        {% for post in posts %}
            <div class="col-md-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4
                shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <ul>
                            <h3 class="mb-0">
                                {{ post.title }}
                            </h3>
                            <p class="card-text mb-auto">
                                {{ post.message }}
                            </p>
                            <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
                                {% if user.is_authenticated and user == post.author %}
                                    <a class="btn btn-primary"
                                       href="{% url 'blog:edit_post' post.id %}">Edit Post</a>
                                    <a class="btn btn-primary"
                                       href="{% url 'blog:delete' post.id %}">Delete</a>
                                    {% endif %}
                            </div>
                        </ul>
                        {% if user.is_authenticated %}
                            <a class="btn btn-primary btn-sm" type="button"
                               href="{% url 'blog:new_post' %}">Add Post</a>
                        {% endif %}
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="200" height="250"
                             xmlns="http://www.w3.org/2000/svg" role="image"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                             focusable="false">
                            <text x="50%" y="50%">
                                {{ post.author.username }}
                            </text>
                            <text x="50%" y="60%">
                                {{ post.timestamp|date:'d.m.y H:i' }}
                            </text>
                        </svg>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>No posts yet.</p>
        {% endfor %}
    </div>
    <!--  Posts block end  -->
{% endblock content %}

blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}

{% block page_header %}

<h2 class="display-5">
    Add a new post on the site
</h2>

{% endblock page_header %}

{% block content %}

<form action="{% url 'blog:new_post' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button class="btn btn-dark">Add post</button>
    {% endbuttons%}
</form>

{% endblock content %}